E_Learning/urls.py
from . import views
from django.urls import path
from django.urls import include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),

    # connecting apps
    path('account/', include('user_auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('article/', include('article.urls')),
    path('forum/', include('forum.urls')),
    path('quiz/', include('quiz.urls')),

    # users will be redirected based on login status
    path('', views.redirect_to_dashboard_or_website),
    path('home/', views.redirect_to_dashboard_or_website),
    path('index/', views.redirect_to_dashboard_or_website),
]

dashboard/urls.py
from . import views
from django.urls import path

app_name = 'dashboard'

urlpatterns = [
    path('', views.displayDashboard, name = 'display_dashboard'),
]

forum/urls.py
from . import views
from django.urls import path
from django.views.generic.base import RedirectView

app_name = 'forum'

urlpatterns = [
    path('home/', views.DisplayForumHome.as_view(), name = 'home'),
    path('question/<slug:slug>', views.DisplayQuestion.as_view(), name = 'question'),

    # redirecting users to the home
    path('', RedirectView.as_view(pattern_name = 'forum:home')),
]

quiz/urls.py
from . import views
from django.urls import path
from django.views.generic.base import RedirectView

app_name = 'quiz'

urlpatterns = [
    # all users
    path('list/', views.ListQuizzes.as_view(), name = 'list'),

    # teacher - arranging the quiz
    path('new/', views.NewQuiz.as_view(), name = 'new_quiz'),
    path('new/<slug:slug>', views.newQuestions, name = 'new_questions'),

    # teacher - evaluating the quiz
    path('review/<slug:slug>', views.reviewStudentAttempts, name = 'review'),
    
    # student - attempting the quiz
    path('attempt/<slug:slug>', views.attemptQuiz, name = 'attempt'),
    path('summary/<slug:slug>', views.displaySummary, name = 'summary'),

    # redirecting the users to quiz
    path('', RedirectView.as_view(pattern_name = 'quiz:list')),
    path('new/', RedirectView.as_view(pattern_name = 'quiz:new_quiz')),
]

forum/models.py
from uuslug import uuslug
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class Question(models.Model):
    title = models.CharField(max_length = 200)
    body = models.TextField()
    created_by = models.ForeignKey(get_user_model(), blank = True, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    slug = models.SlugField(max_length = 200, blank = True, unique = True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = uuslug(self.title, instance=self, max_length=200)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
class Answer(models.Model): 
    question = models.ForeignKey(Question, blank = True, on_delete=models.CASCADE)
    body = models.TextField()
    created_by = models.ForeignKey(get_user_model(), blank = True, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)

forum/forms.py
from . import models
from django import forms

class NewQuestionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['title'].label = ''
        self.fields['body'].label = ''
    
    class Meta:
        model = models.Question
        fields = [
            'title',
            'body',
        ]
        widgets = {
            'title' : forms.TextInput(attrs = {'placeholder' : 'Enter title here',}),
            'body' : forms.Textarea(attrs = {'placeholder' : 'Enter question here'}),
        }

class NewAnswerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['body'].label = ''

    
    class Meta:
        model = models.Answer
        fields = ['body']
        widgets = {
            'body' : forms.Textarea(attrs = {'placeholder' : 'Type answer here'})
        }

forum/views.py
from . import forms
from . import models
from typing import Any
from django.db.models import Count
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin 
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404


# Create your views here.

class DisplayForumHome(FormMixin, ListView):
    """
    Anyone can view the questions posted in the forum. Only students get to ask questions.
    """
    model = models.Question
    form_class = forms.NewQuestionForm
    template_name = 'forum/forum_home.html'

    def get_queryset(self):
        queryset = super().get_queryset()

        # this counts all the answers for each question
        queryset = queryset.annotate(answer_count = Count('answer')).order_by('-created_at')

        return queryset

    @method_decorator(permission_required('forum.add_question', raise_exception = True)) # only logged in students can post
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        return self.form_valid(form) if form.is_valid() else self.form_invalid(form)

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('forum:home')
    
class DisplayQuestion(FormMixin, DetailView):
    """
    Teachers and other students can post answers the question.
    """
    model = models.Question
    form_class = forms.NewAnswerForm
    template_name = 'forum/question.html'

    def get_queryset(self):
        """
        Prefetch related answers for efficiency
        """
        return super().get_queryset().prefetch_related('answer_set')

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()

        answer_set = self.object.answer_set.all() # type: ignore
        context['answer_count'] = answer_set.count()
        context['answer_set'] = answer_set.order_by('-created_at') 

        return context
    
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        return self.form_valid(form) if form.is_valid() else self.form_invalid(form)
            
    def form_valid(self, form):
        answer =  form.save(commit = False)
        answer.question = self.object
        answer.created_by = self.request.user
        answer.save()
        return super().form_valid(form)
        
    def get_success_url(self):
        return reverse_lazy('forum:question', kwargs = {'slug' : self.object.slug}) # type: ignore

forum/templates/forum/forum_home.html
{% extends 'base.html' %}
{% load filter_by_user_group %}


{% block body %}

    <a href="{% url 'dashboard:display_dashboard' %}">Go back to the dashboard</a>

    <h1>Forum</h1>
    
    {% if request.user|has_group:"student" %}
        <br>

        <div style="border: 1px solid black; margin-bottom: 20px; padding: 0px 20px 10px 20px;">
            <form method="POST">
                <h2>Ask a question:</h2>
                {{ form.as_p }}
                {% csrf_token %}

                <input type="submit" value="Submit question">
            </form><br>
        </div>
        
    {% endif %}<br>

    <h2>Recent questions:</h2>

    {% for question in question_list %}
        <hr>
        
        <h3>
            <a href="{% url 'forum:question' question.slug %}">
                {{ question.title }}
            </a>
             - @{{ question.created_by }} at {{ question.created_at }}

        </h3>

        <p>
            {{ question.body|truncatechars:500 }}
        </p>
        <p>Answers: {{ question.answer_count }}
                
        </p>
    {% endfor %}
        
{% endblock body %}
    

forum/templates/forum/question.html
{% extends 'base.html' %}


{% block body %}

    <a href="{% url 'forum:home' %}">Go back to forum home</a>
    <br>

    <div style="margin: 10px 0px 50px 0px;">
        @{{ question.created_by }} at {{ question.created_at }}
        <h1>{{ question.title }}</h1>
        <div style="margin: 0px 10px;">
            <h4>{{ question.body }}</h4>
        </div>
        <br>
    </div>

    
    {% if request.user.is_authenticated %}
        
        <div style="border: 1px solid black; margin-bottom: 70px; padding: 0px 20px 10px 20px;">
            <form method = "POST">
                <h2>Write an answer</h2>
                {{ form.as_p }}

                {% csrf_token %}

                <input type="submit" value="Add answer">
            </form><br>
        </div>
    
    {% endif %}
        
    
    <div>
        <h2>{{ answer_count }} Answers:</h2>
        {% for answer in answer_set %}
            <div style="border: 1px solid black; margin-bottom: 20px; padding: 0px 20px 10px 20px;">
                <h6>@{{ answer.created_by }} at {{ answer.created_at }}</h6>
                <p>
                    {{ answer.body }}
                </p>
            </div>
        {% endfor %}
    </div>
{% endblock body %}
    