E_Learning/urls.py
from . import views
from django.urls import path
from django.urls import include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),

    # connecting apps
    path('account/', include('user_auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('article/', include('article.urls')),
    path('forum/', include('forum.urls')),
    path('quiz/', include('quiz.urls')),

    # users will be redirected based on login status
    path('', views.redirect_to_dashboard_or_website),
    path('home/', views.redirect_to_dashboard_or_website),
    path('index/', views.redirect_to_dashboard_or_website),
]

dashboard/urls.py
from . import views
from django.urls import path

app_name = 'dashboard'

urlpatterns = [
    path('', views.displayDashboard, name = 'display_dashboard'),
]

quiz/urls.py
from . import views
from django.urls import path
from django.views.generic.base import RedirectView

app_name = 'quiz'

urlpatterns = [
    # all users
    path('list/', views.ListQuizzes.as_view(), name = 'list'),

    # teacher - arranging the quiz
    path('new/', views.NewQuiz.as_view(), name = 'new_quiz'),
    path('new/<slug:slug>', views.newQuestions, name = 'new_questions'),

    # teacher - evaluating the quiz
    path('review/<slug:slug>', views.reviewStudentAttempts, name = 'review'),
    
    # student - attempting the quiz
    path('attempt/<slug:slug>', views.attemptQuiz, name = 'attempt'),
    path('summary/<slug:slug>', views.displaySummary, name = 'summary'),

    # redirecting the users to quiz
    path('', RedirectView.as_view(pattern_name = 'quiz:list')),
    path('new/', RedirectView.as_view(pattern_name = 'quiz:new_quiz')),
]

quiz/models.py
from django.contrib.auth import get_user_model
from django.db import models
from uuslug import uuslug

# Create your models here.

class Quiz(models.Model):
    SUBJECTS = (
        ('phy', 'Physics'),
        ('che', 'Chemistry'),
        ('math', 'Math'),
    )
    subject = models.CharField(choices = SUBJECTS, max_length = 4)
    title = models.CharField(max_length = 200)

    created_by = models.ForeignKey(get_user_model(), blank = True, on_delete = models.CASCADE)
    created_at = models.DateField(auto_now_add = True)
    slug = models.SlugField(max_length = 200, blank = True, unique = True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = uuslug(self.title, instance = self, max_length = 200)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)

    def __str__(self):
        return self.title

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    is_correct = models.BooleanField(default = False)

    def __str__(self):
        return self.title

class Attempt(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete = models.CASCADE)
    attempted_by = models.ForeignKey(get_user_model(), blank = True, on_delete = models.CASCADE)
    attempted_at = models.DateTimeField(auto_now_add = True)
    is_successful = models.BooleanField(default = False)

    def __str__(self):
        return f"{str('successful' if self.is_successful else 'unsuccessful')} {self.quiz.title} {str(self.attempted_at)}"

class Response(models.Model):
    attempt = models.ForeignKey(Attempt, blank = True, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, blank = True, on_delete = models.CASCADE)
    choice = models.ManyToManyField(Choice)
    is_correct = models.BooleanField(default = False)
    responded_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return str(self.is_correct)

forum/views.py
from . import forms
from . import models
from typing import Any
from django.db.models import Count
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin 
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404


# Create your views here.

class DisplayForumHome(FormMixin, ListView):
    """
    Anyone can view the questions posted in the forum. Only students get to ask questions.
    """
    model = models.Question
    form_class = forms.NewQuestionForm
    template_name = 'forum/forum_home.html'

    def get_queryset(self):
        queryset = super().get_queryset()

        # this counts all the answers for each question
        queryset = queryset.annotate(answer_count = Count('answer')).order_by('-created_at')

        return queryset

    @method_decorator(permission_required('forum.add_question', raise_exception = True)) # only logged in students can post
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        return self.form_valid(form) if form.is_valid() else self.form_invalid(form)

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('forum:home')
    
class DisplayQuestion(FormMixin, DetailView):
    """
    Teachers and other students can post answers the question.
    """
    model = models.Question
    form_class = forms.NewAnswerForm
    template_name = 'forum/question.html'

    def get_queryset(self):
        """
        Prefetch related answers for efficiency
        """
        return super().get_queryset().prefetch_related('answer_set')

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()

        answer_set = self.object.answer_set.all() # type: ignore
        context['answer_count'] = answer_set.count()
        context['answer_set'] = answer_set.order_by('-created_at') 

        return context
    
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        return self.form_valid(form) if form.is_valid() else self.form_invalid(form)
            
    def form_valid(self, form):
        answer =  form.save(commit = False)
        answer.question = self.object
        answer.created_by = self.request.user
        answer.save()
        return super().form_valid(form)
        
    def get_success_url(self):
        return reverse_lazy('forum:question', kwargs = {'slug' : self.object.slug}) # type: ignore

quiz/views.py
import logging
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.paginator import Paginator

from django.shortcuts import get_object_or_404, get_list_or_404, redirect, render
from django.views.generic import CreateView, ListView
from django.forms import formset_factory
from django.urls import reverse

import core.constants as constants

from . import forms, models

logger = logging.getLogger(__name__)

# TODO replace Httpresponse with http403 whereever the mixin is being used


class ListQuizzes(ListView):
    model = models.Quiz
    template_name = 'quiz/list_of_quizzes.html'
    ordering = ['-created_at', 'title']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_heading'] = constants.GENERATE_PAGE_HEADING(
            'Quizze')  # returns Quizzes
        context['quizzes'] = self.get_queryset()
        context['empty_list_message'] = constants.GENERATE_EMPTY_LIST_MESSAGE(
            'Quiz')
        return context


# --- Teacher arranging a quiz ---

class NewQuiz(PermissionRequiredMixin, CreateView):

    permission_required = 'quiz.add_quiz'
    permission_denied_message = constants.PERMISSION_DENIED_MESSAGE

    model = models.Quiz
    template_name = 'quiz/new_quiz.html'
    # this will take them to the page that adds questions
    fields = ['subject', 'title']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        # type: ignore
        return reverse('quiz:new_questions', kwargs={'slug': self.object.slug}) # type: ignore

# helper method for the view: newQuestion
def save_new_questions_with_choices(request, quiz):
    """
    saves the question object along with 4 optional choice objects, in the db.
    """
    question_form = forms.NewQuestionForm(request.POST)

    ChoiceFormSet = formset_factory(
        forms.NewChoiceForm, formset=forms.BaseChoiceFormSet, extra=4)
    choice_formset = ChoiceFormSet(request.POST)

    if question_form.is_valid() and choice_formset.is_valid():
        question = question_form.save(commit=False)
        question.quiz = quiz
        question.save()

        for choice_form in choice_formset:
            if choice_form.is_valid():
                choice = choice_form.save(commit=False)
                if choice.title:
                    choice.question = question
                    choice.save()
                else:
                    logger.error("Choice title field is empty.")
            else:
                logger.error("Choice form is not valid.")

        return True
    else:
        logger.error("Question form is not valid.")
        return False

@permission_required('quiz.add_quiz', raise_exception=True)
def newQuestions(request, slug): #TODO possible refactor

    quiz = get_object_or_404(
        models.Quiz,
        slug=slug,
        created_by=request.user
    )

    if request.method == 'POST' and save_new_questions_with_choices(request, quiz):
    # TODO everytime I redirect, the quiz is being fetched from db, can we eliminate this extra db hit?
        return redirect('quiz:new_questions', slug) 
    

    # get the forms
    question_form = forms.NewQuestionForm()

    # get the input fields for 4 choices
    ChoiceFormSet = formset_factory(
        forms.NewChoiceForm, formset=forms.BaseChoiceFormSet, extra=4)
    choice_formset = ChoiceFormSet()

    context = {
        'quiz': quiz,
        'question_list': models.Question.objects.filter(quiz=quiz),
        'question_form': question_form,
        'choice_formset': choice_formset,
    }

    return render(request, 'quiz/new_questions.html', context=context)


# --- teacher reviewing student attempts ---

# helper method for the view: reviewStudentAttempts
def group_attempts_by_user(quiz): 
        
        attempts = models.Attempt.objects.filter(quiz = quiz)

        attempts_grouped_by_users = {}

        for attempt in attempts:
            if attempt.attempted_by not in attempts_grouped_by_users:
                attempts_grouped_by_users[attempt.attempted_by] = [attempt]
            else:
                attempts_grouped_by_users[attempt.attempted_by].append(attempt)

        return attempts_grouped_by_users

@permission_required('quiz.add_quiz', raise_exception = True)
def reviewStudentAttempts(request, slug):

    quiz = get_object_or_404(
        models.Quiz,
        slug = slug,
        created_by = request.user
    )

    student_attempts = group_attempts_by_user(quiz)

    context = {
        'quiz' : quiz,
        'student_attempts' : student_attempts,
    }

    return render(request, 'quiz/review_student_attempts.html', context)

# --- student attempting a quiz ---

# region - helper methods for the view: attemptQuiz

def get_quiz_and_question_list(request, slug):
    """
    Gets the quiz and questions. Prefetches the choices for the questions.
    """
    try:
        quiz = models.Quiz.objects.get(slug=slug)

    except models.Quiz.DoesNotExist:
        return redirect('dashboard:display_dashboard')

    question_list = models.Question.objects.filter(
        quiz=quiz).order_by('id').prefetch_related('choice_set')

    return quiz, question_list


def get_attempt(request, quiz):
    """
    Tracks attempts made by the students.
    """
    if 'attempt_id' not in request.session:
        attempt = models.Attempt(
            quiz=quiz,
            attempted_by=request.user,
        )
        attempt.save()
        request.session['attempt_id'] = attempt.id  # type: ignore

    else:
        try:
            attempt = models.Attempt.objects.get(
                id=request.session['attempt_id']
            )
        except models.Attempt.DoesNotExist:
            return redirect('quiz:list')

    return attempt


def evaluate_and_save_response(request, attempt, page_obj):
    """
    Evaluates the response, and saves it in the db.
    """

    # getting the correct choice
    question = page_obj.object_list[0]
    choice_set = question.choice_set.all()
    correct_choice = choice_set.filter(is_correct=True)

    response_form = forms.NewResponseForm(request.POST, page_obj=page_obj)

    if response_form.is_valid():

        selected_choice = response_form.cleaned_data['choice']

        is_correct = selected_choice in correct_choice

        # saving the response in the db
        response = response_form.save(commit=False)
        response.attempt = attempt
        response.question = question
        response.is_correct = is_correct

        response.save()

        response.choice.set([selected_choice])

        return is_correct

    else:
        logger.error("Response form is not valid.")

    return False


def evaluate_attempt(attempt):
    """
    if any response is False, the attempt is unsuccessful
    """
    responses = models.Response.objects.filter(attempt=attempt)

    attempt.is_successful = not any(
        not response.is_correct for response in responses)
    attempt.save()


def control_progression(request, attempt, paginator):
    """
    Controls when the student gets to move on to the next question.
    """

    page_number = request.POST.get('page')
    current_page = paginator.get_page(int(page_number))

    is_correct = evaluate_and_save_response(request, attempt, current_page)

    if not is_correct:
        page_obj = current_page

    elif is_correct and current_page.has_next():
        page_obj = paginator.get_page(int(page_number) + 1)
        is_correct = None

    else:  # student correctly responded to the last question
        evaluate_attempt(attempt)

        if 'attempt_id' in request.session:
            del request.session['attempt_id']

        return None, None

    return page_obj, is_correct

# endregion - helper methods 

@permission_required('quiz.add_attempt', raise_exception=True)
def attemptQuiz(request, slug):
    quiz, question_list = get_quiz_and_question_list(request, slug)

    attempt = get_attempt(request, quiz)

    # ask a single question at a time
    questions_in_a_page = 1
    paginator = Paginator(question_list, questions_in_a_page)
    total_pages = paginator.num_pages
    page_obj = paginator.get_page(1)

    # handle responses to questions
    if request.method == 'POST':
        page_obj, is_correct = control_progression(request, attempt, paginator)

        if page_obj is None and is_correct is None:  # quiz has ENDED
            return redirect('quiz:summary', slug)

    else:
        is_correct = None

    context = {
        'quiz': quiz,
        'page_obj': page_obj,
        'total_pages': total_pages,
        'is_correct': is_correct,
        'response_form': forms.NewResponseForm(page_obj=page_obj),
    }

    return render(request, 'quiz/attempt_quiz.html', context)


@permission_required('quiz.add_attempt', raise_exception=True)
# TODO: refactor the code to make it more maintainable, testable, and modular
def displaySummary(request, slug):
    """
    Displays the summary of the quiz attempt.
    """
    quiz = models.Quiz.objects.prefetch_related('question_set').get(slug=slug)
    questions = quiz.question_set.all()  # type: ignore
    total_questions = int(questions.count())  # type: ignore

    attempts = models.Attempt.objects.filter(
        attempted_by=request.user,
        quiz=quiz,
    ).order_by('attempted_at').prefetch_related('response_set')

    for attempt in attempts:

        responses = attempt.response_set.all().order_by('responded_at') # type: ignore
        correct_responses = int(responses.filter(is_correct=True).count())

        attempt.questions = questions  # type: ignore
        attempt.responses = responses  # type: ignore
        attempt.correct_responses = correct_responses  # type: ignore

    context = {
        'quiz': quiz,
        'total_questions': total_questions,
        'attempt_list': attempts

quiz/templates/quiz/attempt_quiz.html
{% extends 'base.html' %}

{% block body %}
  <h1>{{ quiz.title }}</h1>

  <form method="POST">
    {% csrf_token %}

    <h2>Question {{ page_obj.number }}/ {{ total_pages }}: {{ page_obj.object_list.0.title }}</h2>
    <input type="hidden" name="page" value="{{ page_obj.number }}">

    
    {% if is_correct is False %}
      <div>
        <h4>Incorrect response</h4>
      </div>
    {% endif %}
      

    {{ response_form.as_p }}

    <div>
      <span>
        {% if page_obj.has_next %}
          <input type="submit" value="Check answer">
        {% else %}
          <input type="submit" value="Finish quiz">
        {% endif %}
      </span>
    </div>
  </form>
{% endblock %}

quiz/templates/quiz/list_of_quizzes.html
{% extends 'display_list.html' %}
{% load filter_by_user_group %}

{% block object_page %}
  {% if request.user|has_group:"student" %}
    <h2>
      <a href="{% url 'quiz:attempt' object.slug %}">
        {{ object.title | title }}
      </a>
    </h2>
    {{ object.subject | title }} - {{ object.created_by }}
  {% else %}
    {% if object.created_by == request.user %}
      <h2>
      <a href="{% url 'quiz:review' object.slug %}">
        {{ object.title | title }}
      </a>
    </h2>
    {{ object.created_at }}
    {% endif %}
  {% endif %}
{% endblock %}

quiz/templates/quiz/new_questions.html
{% extends 'base.html' %}

{% block title %}
  Quiz: {{ quiz.title|title }}
{% endblock %}

{% block body %}
  <h1>Quiz: {{ quiz.title|title }}</h1>

  <!-- create question with choices -->
  <form method="POST">
    <h2>Add a question:</h2>

    <div style="border: 1px solid black; padding: 0px 20px 20px 20px ;">
      {{ question_form.as_p }}

      <p>Add choices:</p>

      <div style="margin-left: 20px;">
        {{ choice_formset.management_form }}
        <ol type="A">
          {% for form in choice_formset %}
            <li>
              <div style="display: flex; margin-bottom: 10px;">
                <div style="flex: 1;">{{ form.title.label_tag }} {{ form.title }}</div>
                <div style="flex: 5;">{{ form.is_correct.label_tag }} {{ form.is_correct }}</div>
              </div>
            </li>
          {% endfor %}
        </ol>
      </div>

      {% csrf_token %}

      <br />
      <input type="submit" value="Add question" />
    </div>
  </form>
  <br />

  <h2>Questions:</h2>
  <hr />

  <!-- list of questions already defined -->
  <ol>
    {% for question in question_list %}
      <li>
        <h3>{{ question.title|title }}</h3>

        {% if question.choice_set.all %}
          <p>Choices:</p>
          <ol type="a">
            {% for choice in question.choice_set.all %}
              <li>
                {{ choice.title }}
                {% if choice.is_correct %}
                  (Correct)
                {% endif %}
              </li>
            {% endfor %}
          </ol>
        {% else %}
          <p>No choice available</p>
        {% endif %}
      </li>
      {% empty %}Nothing yet
    {% endfor %}
  </ol>

  <br />

  {% if question_list %}
    <h3><a href="{% url 'dashboard:display_dashboard' %}">Assign the Quiz</a></h3>
  {% else %}
    <h3><a>Assign the Quiz</a></h3>
  {% endif %}
{% endblock %}

quiz/templates/quiz/new_quiz.html
{% extends 'base.html' %}


{% block title %}
    New Quiz
{% endblock title %}


{% block body %}

    <a href="{% url 'dashboard:display_dashboard' %}">Go back to the dashboard</a>

    <h1>Arrange Quiz</h1>
    
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}

        <input type="submit" value="Arrange Quiz">
    </form>

{% endblock body %}
    

quiz/templates/quiz/quiz_summary.html
{% extends 'base.html' %}

{% block body %}
  <h1>{{ quiz.title|title }}</h1>

  <ol>
    {% for attempt in attempt_list %}
      <li>
        <h2>
          {{ attempt.attempted_at }} | 
          ( {% if attempt.is_successful %}Successful{% else %}Unsuccessful{% endif %} )
          <!-- Correct responses: {{ attempt.correct_responses }}/ {{ total_questions }} -->
        </h2>

        <ol type="A">
          
          {% for question in attempt.questions %}
            <li>
              <h4>
                {{ question.title | title }}
                
                <ol type="i">
                    {% for response in question.response_set.all %}
                        {% if response in attempt.responses %}
                          <li>
                            Choice: 
                            {% for choice in response.choice.all %}
                              {{ choice.title }}
                            {% endfor %}

                            &nbsp
                            
                            {% if response.is_correct %}
                              (Correct)
                            {% else %}
                              (Incorrect)
                            {% endif %}
                          </li>
                        {% endif %}
                    {% endfor %}
                </ol>    
              </h4>
            </li>

            {% empty %}
            <!-- empty list warning -->
          {% endfor %}
            
        </ol>
      </li>

      {% empty %}
      <!-- empty list warning -->
    {% endfor %}
  </ol>

  <a href="{% url 'dashboard:display_dashboard' %}">Go back to the dashboard</a>
{% endblock %}

quiz/templates/quiz/review_student_attempts.html
{% extends 'base.html' %}


{% block body %}
    <a href="{% url 'quiz:list' %}">Go back to the list</a>

    <h1>{{ quiz.title }}</h1>


    <h2>Attempts:</h2>

    
    {% for user, attempts in student_attempts.items %}
        @{{ user.username }} 

        <ol>
            {% for attempt in attempts %}
                <li>
                    {{ attempt.attempted_at }} | 
                    ( 
                    {% if attempt.is_successful %}
                        Successful
                    {% else %}
                        Unsuccessful
                    {% endif %} 
                    )
                </li>
            {% empty %}
                Something's wrong
            {% endfor %}
        </ol> 
    {% empty %}
        No attempts yet
    {% endfor %}

        
{% endblock body %}
    