E_Learning/urls.py
from . import views
from django.urls import path
from django.urls import include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),

    # connecting apps
    path('account/', include('user_auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('article/', include('article.urls')),
    path('forum/', include('forum.urls')),
    path('quiz/', include('quiz.urls')),

    # users will be redirected based on login status
    path('', views.redirect_to_dashboard_or_website),
    path('home/', views.redirect_to_dashboard_or_website),
    path('index/', views.redirect_to_dashboard_or_website),
]

article/urls.py
from . import views
from django.urls import path
from django.views.generic.base import RedirectView

app_name = 'article'

urlpatterns = [
    path('new/', views.NewArticle.as_view(), name = 'new'),
    path('read/<slug:slug>', views.ReadArticle.as_view(), name = 'view'),
    path('list/', views.ListArticles.as_view(), name = 'list'),

    # redirecting the users to article list
    path('', RedirectView.as_view(pattern_name = 'article:list')),
    path('read/', RedirectView.as_view(pattern_name = 'article:list')),
]

dashboard/urls.py
from . import views
from django.urls import path

app_name = 'dashboard'

urlpatterns = [
    path('', views.displayDashboard, name = 'display_dashboard'),
]

quiz/urls.py
from . import views
from django.urls import path
from django.views.generic.base import RedirectView

app_name = 'quiz'

urlpatterns = [
    # all users
    path('list/', views.ListQuizzes.as_view(), name = 'list'),

    # teacher - arranging the quiz
    path('new/', views.NewQuiz.as_view(), name = 'new_quiz'),
    path('new/<slug:slug>', views.newQuestions, name = 'new_questions'),

    # teacher - evaluating the quiz
    path('review/<slug:slug>', views.reviewStudentAttempts, name = 'review'),
    
    # student - attempting the quiz
    path('attempt/<slug:slug>', views.attemptQuiz, name = 'attempt'),
    path('summary/<slug:slug>', views.displaySummary, name = 'summary'),

    # redirecting the users to quiz
    path('', RedirectView.as_view(pattern_name = 'quiz:list')),
    path('new/', RedirectView.as_view(pattern_name = 'quiz:new_quiz')),
]

user_auth/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'user_auth'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name = 'user_auth/user_auth.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

dashboard/views.py
from django.shortcuts import render
from core.constants import PERMISSION_DENIED_MESSAGE
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied

# Create your views here.

@login_required
def displayDashboard(request):
    context = {}
    user = request.user

    if request.user.groups.filter(name='teacher').exists():
        template = 'dashboard/teacher_dashboard.html'
    elif request.user.groups.filter(name='student').exists():
        template = 'dashboard/student_dashboard.html'
    else:
        raise PermissionDenied(PERMISSION_DENIED_MESSAGE)

    return render(request, template, context = context)
        

dashboard/templates/dashboard/base_dashboard.html
{% extends 'base.html' %}

{% block title %}
  {{ user.username|title }}'s Dashboard
{% endblock %}

{% block body %}

  <h1>
    {% block greeting %}
      Welcome, {{ user.username|title }}!
    {% endblock %}
  </h1>

  <form method="POST" action="{% url 'user_auth:logout' %}">
    {% csrf_token %}
    <input type="submit" value="logout" />
  </form>


  <!-- navigation/ tools -->
  <div style="display: flex; border: 1px solid black; margin-top: 20px;">

    <div style="flex: 1; padding: 30px 20px;">
        {% block column1 %}
        {% endblock %}
    </div>

    <div style="flex: 1; padding: 30px 20px;">
        {% block column2 %}
        {% endblock %}
    </div>

    <div style="flex: 1; padding: 30px 20px;">
        {% block column3 %}
        {% endblock %}
    </div>

  </div>
{% endblock %}

dashboard/templates/dashboard/student_dashboard.html
{% extends 'dashboard/base_dashboard.html' %}


{% block column1 %}
    <a href="{% url 'article:list' %}">Articles</a>
{% endblock column1 %}


{% block column2 %}
    <a href="{% url 'quiz:list' %}">Quizzes</a>
{% endblock column2 %}


{% block column3 %}
    <a href="{% url 'forum:home' %}">Forum</a>
{% endblock column3 %}
    
    

dashboard/templates/dashboard/teacher_dashboard.html
{% extends 'dashboard/base_dashboard.html' %}

{% block column1 %}

    <form method="POST" action="{% url 'article:new' %}">
        {% csrf_token %}
        <input type="submit", value="New Article">
    </form>

    <br>
    <a href="{% url 'article:list' %}">View Published Articles</a>

{% endblock %}

{% block column2 %}

    <form method="POST" action="{% url 'quiz:new_quiz' %}">
        {% csrf_token %}
        <input type="submit", value="New Quiz">
    </form>

    <br>
    <!-- we'll have to change this, the following link will take the teacher to the results page  -->
    <a href="{% url 'quiz:list' %}">View Responses to Assigned Quizzes</a> 

{% endblock %}

{% block column3 %}
        <a href="{% url 'forum:home' %}">Forum</a>
{% endblock %}